"""Frame, source metadata, and the abstract base every video source implements.

This module is the adapter seam of the whole system. Everything downstream --
inference, the temporal filter, the WebRTC track, the incident log -- consumes
:class:`Frame` objects and never knows whether they came off a drone radio, a
capture card, or a file on disk. That is what lets the pipeline be developed
and regression-tested with no drone in the room.

**pts is the contract.** ``Frame.pts`` is presentation time in seconds on the
*media* timeline: the same timeline the browser exposes as
``video.currentTime`` and the same number that goes into
``FrameDetections.pts``. It is the only field that lets a tablet draw a box
over the frame it was computed from (see ``docs/CONTRACT.md``). Three
properties are guaranteed here and relied upon everywhere else:

1. **Zero-based.** The first frame emitted in a session has ``pts == 0.0``.
   Containers may start at an arbitrary offset; live sources restart from zero
   on every reconnect. Rebasing once, here, means the rest of the system has a
   single continuous timeline and ``stream_start_pts`` is meaningful.
2. **Strictly monotonic.** ``pts`` never repeats and never goes backwards --
   across a decode glitch, a file loop, or a radio dropout. A backwards pts
   would make the tablet's nearest-pts overlay match ambiguous, and an
   ambiguous match is a box drawn on the wrong frame.
3. **Real, when the source has real timestamps.** Container timestamps are
   used as given (rebased). Only when a source genuinely has none is pts
   synthesised from the frame index or from arrival wall-clock, and
   :attr:`SourceInfo.pts_origin` then says so out loud. Silently faking
   timestamps would hide variable-rate sources and frame drops from the
   overlay-synchronisation code that has to cope with them.

``rtp_ts`` is left ``None`` by every source in this package, on purpose. The
tier-1 alignment in ``docs/CONTRACT.md`` needs the RTP timestamp *the browser
will actually see*, which is generated by the sender (aiortc) when the frame is
packetised -- not by the decoder that produced the frame. Deriving one here
from pts would look like tier-1 precision while being an invention. The stream
layer fills it in if it can.

The two backend readers (:class:`PyAVReader`, :class:`OpenCVReader`) live here
rather than in a module of their own because four of the five sources need
them; every heavy import inside them is deferred to :meth:`open` so that this
module, and the pure-logic tests, import fine on a machine with neither PyAV
nor OpenCV installed.
"""

from __future__ import annotations

import abc
import math
import os
import threading
import time
from dataclasses import dataclass, field, replace
from typing import Any, Iterator, Protocol, Sequence

import numpy as np

from station.core.config import SourceConfig
from station.core.types import utc_now_iso

__all__ = [
    "IngestError",
    "MissingDependencyError",
    "SourceUnavailableError",
    "SourceConfigError",
    "PtsOrigin",
    "Frame",
    "SourceInfo",
    "SourceStats",
    "PtsClock",
    "FpsDecimator",
    "ReconnectPolicy",
    "FrameReader",
    "PyAVReader",
    "OpenCVReader",
    "FrameSource",
    "ReconnectingSource",
    "DEFAULT_FPS",
    "MIN_PTS_STEP",
]

#: Used only when a source cannot report its own rate. 30 is the SIYI MK15
#: downlink default and a harmless guess for a file whose header is unhelpful.
DEFAULT_FPS = 30.0

#: Smallest gap we will ever leave between two consecutive pts values when
#: repairing a non-monotonic source. It has to survive the wire format:
#: ``FrameDetections.to_wire`` rounds pts to 4 decimal places, so anything
#: below 1e-4 s could collapse two frames onto one timestamp after
#: serialisation. 1 ms is comfortably above that and far below a frame period.
MIN_PTS_STEP = 1e-3


class IngestError(RuntimeError):
    """Base class for every failure raised by this package."""


class MissingDependencyError(IngestError):
    """A backend needed for this source type is not installed.

    Raised at :meth:`FrameSource.open` time, never at import time. The whole
    package must import cleanly on a laptop with no codecs so that the pure
    logic can be tested there.
    """

    def __init__(self, package: str, purpose: str, install: str) -> None:
        super().__init__(
            f"{purpose} needs the '{package}' package, which is not installed. "
            f"Install it with: {install}"
        )
        self.package = package
        self.install = install


class SourceUnavailableError(IngestError):
    """The source could not be opened, or an open source failed mid-stream."""


class SourceConfigError(IngestError, ValueError):
    """The SourceConfig cannot describe a source that could be opened."""


class PtsOrigin:
    """Where a source's presentation timestamps actually came from.

    Reported in :attr:`SourceInfo.pts_origin`. Downstream code is entitled to
    know: ``CONTAINER`` timestamps reflect real capture timing including
    jitter and drops, whereas ``FRAME_INDEX`` timestamps are a uniform fiction
    that will not line up with a variable-rate stream.
    """

    #: Real timestamps decoded from the container or stream.
    CONTAINER = "container"
    #: frame_index / nominal_fps. Used when the container has no timestamps.
    FRAME_INDEX = "frame_index"
    #: Arrival time on the station's monotonic clock. Used for capture devices,
    #: where arrival time is the only timing information that exists.
    WALL_CLOCK = "wall_clock"
    #: Computed by a generator that defines its own timeline (synthetic).
    GENERATED = "generated"
    #: Not yet known -- no frame has been read.
    UNKNOWN = "unknown"

    ALL = (CONTAINER, FRAME_INDEX, WALL_CLOCK, GENERATED, UNKNOWN)


@dataclass(frozen=True, slots=True, eq=False)
class Frame:
    """One decoded video frame on its way into the pipeline.

    Attributes:
        image: ``HxWx3`` ``uint8`` array in **BGR** channel order. BGR because
            that is what OpenCV and ultralytics both take by default, so the
            inference stage does not have to guess or convert.
        frame_id: Sequence number of frames *emitted by this source*, starting
            at 0. Frames dropped by rate decimation are not counted, so
            ``frame_id`` matches one-for-one with the ``frame_id`` in the
            incident log.
        pts: Presentation time in seconds on the media timeline. Zero-based
            and strictly increasing -- see the module docstring.
        wall_time: RFC 3339 UTC stamp of when the station handled the frame.
            Forensic only. Never used for overlay alignment.
        width: Frame width in pixels.
        height: Frame height in pixels.
        rtp_ts: 90 kHz RTP timestamp, when a layer that knows the real one
            supplies it. Always ``None`` from this package -- see module
            docstring.
        source_pts: The raw timestamp from the container, before rebasing and
            monotonicity repair. Kept for forensics; ``None`` when the source
            had no timestamp for this frame.
        pts_synthesised: True when :attr:`pts` for *this* frame was invented
            rather than decoded. A source can be mostly real and occasionally
            not.

    ``eq`` is disabled: two frames are never meaningfully "equal", and the
    generated ``__eq__`` would compare numpy arrays and raise on the
    ambiguous-truth-value trap.
    """

    image: np.ndarray
    frame_id: int
    pts: float
    wall_time: str = field(default_factory=utc_now_iso)
    width: int = 0
    height: int = 0
    rtp_ts: int | None = None
    source_pts: float | None = None
    pts_synthesised: bool = False

    def __post_init__(self) -> None:
        img = self.image
        if not isinstance(img, np.ndarray):
            raise TypeError(f"Frame.image must be a numpy array, got {type(img).__name__}")
        if img.ndim != 3 or img.shape[2] != 3:
            raise ValueError(f"Frame.image must be HxWx3 BGR, got shape {img.shape}")
        if img.dtype != np.uint8:
            raise ValueError(f"Frame.image must be uint8, got {img.dtype}")
        if not math.isfinite(float(self.pts)):
            raise ValueError(f"Frame.pts must be finite, got {self.pts!r}")
        object.__setattr__(self, "pts", float(self.pts))
        if self.width <= 0:
            object.__setattr__(self, "width", int(img.shape[1]))
        if self.height <= 0:
            object.__setattr__(self, "height", int(img.shape[0]))
        if (self.height, self.width) != img.shape[:2]:
            raise ValueError(
                f"Frame declares {self.width}x{self.height} but image is "
                f"{img.shape[1]}x{img.shape[0]}"
            )

    @property
    def shape(self) -> tuple[int, int]:
        """``(width, height)`` in pixels."""
        return (self.width, self.height)

    def __repr__(self) -> str:  # arrays must never be printed into a log line
        return (
            f"Frame(frame_id={self.frame_id}, pts={self.pts:.4f}, "
            f"{self.width}x{self.height}, synthesised_pts={self.pts_synthesised})"
        )


@dataclass(frozen=True, slots=True)
class SourceInfo:
    """What a source is and how it behaves. Available after :meth:`open`.

    Attributes:
        type: The ``SourceConfig.type`` this source was built from.
        uri: The source URI, used as ``FrameDetections.source_id``.
        width: Native frame width, 0 until the first frame confirms it.
        height: Native frame height, 0 until the first frame confirms it.
        fps: Native source rate, before decimation.
        target_fps: Rate cap applied by this layer, or ``None`` for source rate.
        backend: Which decoder is actually running ("PyAV", "OpenCV", ...).
        pts_origin: One of :class:`PtsOrigin`. Read it before trusting pts to
            reflect real capture timing.
        is_live: True when frames arrive in real time and cannot be rewound.
            A live source that is not read fast enough loses frames; a file
            source just blocks.
        notes: Human-readable caveats accumulated while opening and reading,
            e.g. that timestamps had to be synthesised. Intended for the
            operator-facing log line at startup.
    """

    type: str
    uri: str
    width: int = 0
    height: int = 0
    fps: float = DEFAULT_FPS
    target_fps: float | None = None
    backend: str = "unknown"
    pts_origin: str = PtsOrigin.UNKNOWN
    is_live: bool = False
    notes: tuple[str, ...] = ()

    @property
    def resolution(self) -> tuple[int, int]:
        """``(width, height)`` in pixels; ``(0, 0)`` before the first frame."""
        return (self.width, self.height)

    @property
    def output_fps(self) -> float:
        """Nominal rate handed downstream, after decimation."""
        if self.target_fps is None:
            return self.fps
        return min(self.fps, float(self.target_fps))

    def describe(self) -> str:
        """One-line summary for the startup log."""
        res = f"{self.width}x{self.height}" if self.width else "size unknown"
        rate = f"{self.fps:.3g} fps"
        if self.target_fps is not None:
            rate += f" -> {self.output_fps:.3g} fps"
        bits = [f"{self.type}:{self.uri or '-'}", res, rate, f"via {self.backend}", f"pts={self.pts_origin}"]
        line = " | ".join(bits)
        if self.notes:
            line += " | " + "; ".join(self.notes)
        return line


@dataclass(slots=True)
class SourceStats:
    """Counters a pipeline needs to fill in :class:`PipelineStatus`.

    Deliberately separates the three ways a frame can fail to reach inference:
    decimation (intentional), decode errors (a fault), and reconnects (a link
    problem). Collapsing them into one "dropped" number would hide a failing
    radio behind a configured frame-rate cap.
    """

    frames_in: int = 0
    frames_out: int = 0
    #: Dropped on purpose to honour ``target_fps``.
    decimated: int = 0
    #: Frames whose pts had to be repaired to stay monotonic.
    pts_repairs: int = 0
    #: Frames whose pts had to be invented because the source supplied none.
    pts_synthesised: int = 0
    reconnects: int = 0
    decode_errors: int = 0
    #: True while a live source is between attempts. The status layer turns
    #: this into an operator-facing note; it is a pipeline fact, not a claim
    #: about the scene.
    reconnecting: bool = False
    last_error: str | None = None
    opened_monotonic: float | None = None

    @property
    def elapsed_s(self) -> float:
        """Wall seconds since the source was opened."""
        if self.opened_monotonic is None:
            return 0.0
        return max(0.0, time.monotonic() - self.opened_monotonic)

    @property
    def measured_source_fps(self) -> float | None:
        """Frames arriving per wall second, or ``None`` before enough data.

        For a file decoded flat out this is far above the file's own rate --
        that is honest, not a bug: it is the rate at which frames really
        arrived.
        """
        elapsed = self.elapsed_s
        if elapsed <= 0.0 or self.frames_in < 2:
            return None
        return self.frames_in / elapsed

    @property
    def measured_output_fps(self) -> float | None:
        """Frames handed downstream per wall second."""
        elapsed = self.elapsed_s
        if elapsed <= 0.0 or self.frames_out < 2:
            return None
        return self.frames_out / elapsed


class PtsClock:
    """Turns whatever timestamps a source offers into a lawful media timeline.

    Guarantees the three properties in the module docstring: zero-based,
    strictly monotonic, and honest about where each value came from. One
    instance per source; not thread-safe (a source is read by one thread).

    Args:
        nominal_fps: Source rate, used for the synthetic step and for the size
            of the gap inserted at a loop point.
        mode: Preferred origin -- :attr:`PtsOrigin.CONTAINER` for anything with
            real timestamps, :attr:`PtsOrigin.WALL_CLOCK` for capture devices,
            :attr:`PtsOrigin.FRAME_INDEX` for files whose container has none.
        min_step: Smallest permitted increment when repairing a stall or a
            backwards jump.
    """

    def __init__(
        self,
        nominal_fps: float | None = None,
        mode: str = PtsOrigin.CONTAINER,
        min_step: float = MIN_PTS_STEP,
    ) -> None:
        if mode not in PtsOrigin.ALL:
            raise ValueError(f"unknown pts mode {mode!r}; expected one of {PtsOrigin.ALL}")
        fps = float(nominal_fps) if nominal_fps and nominal_fps > 0 else DEFAULT_FPS
        self._step = 1.0 / fps
        self._mode = mode
        self._min_step = max(float(min_step), 0.0) or MIN_PTS_STEP
        self._raw_origin: float | None = None
        self._wall_origin: float | None = None
        self._offset = 0.0
        self._pending_advance = 0.0
        self._last: float | None = None
        self._count = 0
        self.repairs = 0
        self.synthesised = 0
        #: Origin of the most recent stamp; the source copies this into
        #: SourceInfo once the first frame has proved what the source really is.
        self.origin = PtsOrigin.UNKNOWN

    @property
    def last(self) -> float | None:
        """Most recently issued pts, or ``None`` before the first frame."""
        return self._last

    @property
    def nominal_step(self) -> float:
        """One nominal frame period in seconds."""
        return self._step

    def stamp(self, raw_pts: float | None = None) -> float:
        """Map one source timestamp onto the media timeline.

        Args:
            raw_pts: The container's timestamp in seconds, or ``None`` when the
                source has none for this frame.

        Returns:
            A strictly increasing, zero-based media timestamp in seconds.
        """
        usable = raw_pts is not None and math.isfinite(float(raw_pts))
        if usable and self._mode in (PtsOrigin.CONTAINER, PtsOrigin.GENERATED):
            raw = float(raw_pts)  # type: ignore[arg-type]
            if self._raw_origin is None:
                self._raw_origin = raw
                self._offset = self._resume_base()
            candidate = (raw - self._raw_origin) + self._offset
            origin = self._mode
            synthesised = False
        elif self._mode == PtsOrigin.WALL_CLOCK:
            now = time.monotonic()
            if self._wall_origin is None:
                self._wall_origin = now
                self._offset = self._resume_base()
            candidate = (now - self._wall_origin) + self._offset
            origin = PtsOrigin.WALL_CLOCK
            synthesised = True
        else:
            # No timestamp and no clock worth reading: uniform frame periods.
            # Honest but lossy -- a dropped frame is invisible in this timeline,
            # which is exactly why pts_origin is published.
            if self._last is None:
                candidate = self._resume_base()
            else:
                candidate = self._last + self._step
            origin = PtsOrigin.FRAME_INDEX
            synthesised = True

        if synthesised:
            self.synthesised += 1

        # Monotonicity is repaired rather than trusted. Real streams do go
        # backwards: a decoder resync, an RTSP source that restarts its clock
        # without us noticing, a container with a broken index. Downstream,
        # a repeated or reversed pts means the tablet cannot tell which frame a
        # box belongs to, so we force a gap and count it.
        if self._last is not None and candidate <= self._last + (self._min_step / 2.0):
            candidate = self._last + self._min_step
            self.repairs += 1

        self._last = candidate
        self._count += 1
        self._pending_advance = 0.0
        self.origin = origin
        return candidate

    def discontinuity(self, advance_s: float | None = None) -> None:
        """Declare that the underlying stream restarted its own clock.

        Called on a file loop and after every reconnect. The media timeline
        continues forward across the seam instead of jumping back to zero,
        because the tablet's overlay buffer matches on pts and a timeline that
        rewinds would match new detections against old frames.

        Args:
            advance_s: How far to advance the media timeline across the seam.
                For a reconnect, pass the measured outage in wall seconds so the
                timeline reflects the time the operator actually lost. For a
                loop, one frame period (the default) keeps playback continuous.
        """
        advance = self._step if advance_s is None else max(float(advance_s), self._min_step)
        self._pending_advance = advance
        self._raw_origin = None
        self._wall_origin = None

    def _resume_base(self) -> float:
        """Media time the next epoch starts at."""
        if self._last is None:
            return 0.0
        return self._last + max(self._pending_advance, self._min_step)


class FpsDecimator:
    """Drops frames to honour ``SourceConfig.target_fps``, using pts.

    Decimating by pts rather than by sleeping matters twice over. On a live
    source, sleeping inside the read loop would let the socket buffer fill and
    turn a rate cap into growing latency -- on a fire ground, latency is the
    one thing the overlay cannot buy back. On a file source, sleeping would
    make a regression test run in real time instead of in milliseconds.

    Dropping frames can never break pts monotonicity: it only removes values
    from an already increasing sequence.
    """

    def __init__(self, target_fps: float | None) -> None:
        if target_fps is not None and float(target_fps) <= 0:
            raise SourceConfigError(f"source.target_fps must be positive or null, got {target_fps}")
        self._period = None if target_fps is None else 1.0 / float(target_fps)
        self._next_due: float | None = None
        self.dropped = 0

    @property
    def period(self) -> float | None:
        """Minimum media-seconds between emitted frames, or ``None``."""
        return self._period

    def accept(self, pts: float) -> bool:
        """Decide whether the frame at ``pts`` should be handed downstream."""
        if self._period is None:
            return True
        if self._next_due is None:  # the first frame is always kept
            self._next_due = pts + self._period
            return True
        if pts + 1e-9 >= self._next_due:
            self._next_due += self._period
            # After a gap (reconnect, stall) the schedule is far behind; resync
            # instead of emitting a burst of back-to-back frames to catch up.
            if self._next_due <= pts:
                self._next_due = pts + self._period
            return True
        self.dropped += 1
        return False

    def reset(self) -> None:
        """Forget the schedule, e.g. across a discontinuity."""
        self._next_due = None


class ReconnectPolicy:
    """Exponential backoff with jitter, interruptible by :meth:`cancel`.

    ``SourceConfig.reconnect_s`` sets the first delay. Backing off matters
    because the common failure is not a one-off: the drone is behind a ridge
    and will be for a while, and hammering the radio link with reconnects for
    minutes costs bandwidth the video needs when it does come back. Capping
    the backoff matters just as much -- the link *will* return, and the
    pipeline has to notice within seconds rather than minutes.
    """

    def __init__(
        self,
        base_delay_s: float,
        max_delay_s: float = 15.0,
        max_attempts: int | None = None,
        jitter: float = 0.2,
    ) -> None:
        self._base = max(float(base_delay_s), 0.0)
        self._max = max(float(max_delay_s), self._base)
        self._max_attempts = max_attempts
        self._jitter = min(max(float(jitter), 0.0), 1.0)
        self._cancel = threading.Event()
        self.attempts = 0

    @property
    def exhausted(self) -> bool:
        """True when the attempt budget is used up (never, by default)."""
        return self._max_attempts is not None and self.attempts >= self._max_attempts

    @property
    def cancelled(self) -> bool:
        return self._cancel.is_set()

    def reset(self) -> None:
        """Called after a successful read: the link is healthy again."""
        self.attempts = 0

    def cancel(self) -> None:
        """Interrupt a waiting :meth:`wait`, from any thread.

        This is how ``close()`` gets a source out of a reconnect loop without
        waiting out the backoff.
        """
        self._cancel.set()

    def next_delay(self) -> float:
        """Delay before the next attempt, in seconds."""
        delay = min(self._base * (2.0 ** self.attempts), self._max)
        if self._jitter:
            # Deterministic jitter (derived from the attempt count) rather than
            # random: it still de-synchronises retries between several sources
            # sharing a link, and it keeps test runs reproducible.
            phase = ((self.attempts * 2654435761) % 1000) / 1000.0
            delay *= 1.0 + self._jitter * (phase - 0.5) * 2.0
        return max(delay, 0.0)

    def wait(self) -> bool:
        """Sleep for the next backoff interval.

        Returns:
            True if the wait completed, False if it was cancelled by
            :meth:`cancel` (the source is closing and must not retry).
        """
        delay = self.next_delay()
        self.attempts += 1
        if delay <= 0.0:
            return not self._cancel.is_set()
        return not self._cancel.wait(delay)


class FrameReader(Protocol):
    """What a backend must provide for :class:`ReconnectingSource` to drive it."""

    width: int
    height: int
    fps: float
    backend: str

    def open(self) -> None: ...

    def close(self) -> None: ...

    def next(self) -> tuple[np.ndarray, float | None] | None:
        """Return ``(bgr_image, raw_pts_or_None)``, or ``None`` at end of stream."""


class PyAVReader:
    """One PyAV container, decoded to BGR frames with container timestamps.

    Preferred over OpenCV everywhere it works: PyAV exposes real presentation
    timestamps and the demuxer options that make an RTSP link low-latency,
    both of which ``cv2.VideoCapture`` hides behind a global environment
    variable.
    """

    def __init__(
        self,
        uri: str,
        *,
        options: dict[str, str] | None = None,
        container_format: str | None = None,
        open_timeout_s: float | None = 8.0,
        read_timeout_s: float | None = 8.0,
        thread_type: str = "AUTO",
    ) -> None:
        self.uri = uri
        self.backend = "PyAV"
        self.width = 0
        self.height = 0
        self.fps = DEFAULT_FPS
        self.has_container_pts = False
        self._options = dict(options or {})
        self._format = container_format
        self._open_timeout = open_timeout_s
        self._read_timeout = read_timeout_s
        self._thread_type = thread_type
        self._av: Any = None
        self._container: Any = None
        self._stream: Any = None
        self._frames: Iterator[Any] | None = None
        self._time_base: float | None = None

    def open(self) -> None:
        """Open the container and select its first video stream.

        Raises:
            MissingDependencyError: PyAV is not installed.
            SourceUnavailableError: the container could not be opened or has no
                video stream.
        """
        try:
            import av  # noqa: PLC0415 -- lazy on purpose; see module docstring
        except ImportError as exc:
            raise MissingDependencyError("av", f"decoding {self.uri!r}", "pip install av") from exc
        self._av = av
        kwargs: dict[str, Any] = {"options": self._options}
        if self._format:
            kwargs["format"] = self._format
        if self._open_timeout is not None or self._read_timeout is not None:
            kwargs["timeout"] = (self._open_timeout, self._read_timeout)
        try:
            try:
                self._container = av.open(self.uri, **kwargs)
            except TypeError:
                # PyAV < 9 has no timeout argument. Better to open without one
                # than to refuse to run on an older wheel.
                kwargs.pop("timeout", None)
                self._container = av.open(self.uri, **kwargs)
        except Exception as exc:  # av raises a family of FFmpeg errors
            raise SourceUnavailableError(f"PyAV could not open {self.uri!r}: {exc}") from exc

        streams = self._container.streams.video
        if not streams:
            self.close()
            raise SourceUnavailableError(f"{self.uri!r} has no video stream")
        self._stream = streams[0]
        try:
            # Frame-threaded decoding adds latency (the decoder holds frames
            # back); slice threading does not. AUTO picks per codec, and for
            # H.264 over a radio link the difference is visible.
            self._stream.thread_type = self._thread_type
        except Exception:  # pragma: no cover - older PyAV builds
            pass
        ctx = self._stream.codec_context
        self.width = int(getattr(ctx, "width", 0) or 0)
        self.height = int(getattr(ctx, "height", 0) or 0)
        self.fps = _rate_of(self._stream)
        tb = getattr(self._stream, "time_base", None)
        self._time_base = float(tb) if tb else None
        self._frames = self._container.decode(self._stream)

    def next(self) -> tuple[np.ndarray, float | None] | None:
        """Decode the next frame.

        Returns:
            ``(bgr_image, raw_pts_seconds_or_None)``, or ``None`` at clean end
            of stream.

        Raises:
            SourceUnavailableError: the stream failed mid-decode. Callers that
                can reconnect treat this the same as end of stream.
        """
        if self._frames is None:
            raise SourceUnavailableError("PyAVReader.next() before open()")
        try:
            frame = next(self._frames, None)
        except StopIteration:  # pragma: no cover - next() default covers this
            frame = None
        except Exception as exc:
            raise SourceUnavailableError(f"decode failed on {self.uri!r}: {exc}") from exc
        if frame is None:
            return None
        pts = self._frame_pts(frame)
        if pts is not None:
            self.has_container_pts = True
        try:
            image = frame.to_ndarray(format="bgr24")
        except Exception as exc:
            raise SourceUnavailableError(f"colour conversion failed on {self.uri!r}: {exc}") from exc
        if not self.width or not self.height:
            self.height, self.width = int(image.shape[0]), int(image.shape[1])
        return image, pts

    def _frame_pts(self, frame: Any) -> float | None:
        """Seconds on the container timeline, or ``None`` if it has none."""
        t = getattr(frame, "time", None)  # PyAV already applies time_base here
        if t is not None and math.isfinite(float(t)):
            return float(t)
        raw = getattr(frame, "pts", None)
        if raw is None or self._time_base is None:
            return None
        return float(raw) * self._time_base

    def seek_start(self) -> None:
        """Rewind to the beginning, for a looping file source.

        Raises:
            SourceUnavailableError: the container is not seekable.
        """
        if self._container is None or self._stream is None:
            raise SourceUnavailableError("PyAVReader.seek_start() before open()")
        try:
            self._container.seek(0, stream=self._stream)
            self._frames = self._container.decode(self._stream)
        except Exception as exc:
            raise SourceUnavailableError(f"cannot rewind {self.uri!r}: {exc}") from exc

    def close(self) -> None:
        """Release the container. Safe to call twice."""
        self._frames = None
        self._stream = None
        container, self._container = self._container, None
        if container is not None:
            try:
                container.close()
            except Exception:  # pragma: no cover - closing a dead socket
                pass


class OpenCVReader:
    """``cv2.VideoCapture`` fallback: files, RTSP/RTMP URLs, capture devices.

    Used where PyAV is absent, and preferred for USB capture devices, whose
    pixel-format and buffering controls OpenCV exposes directly.
    """

    def __init__(
        self,
        target: str | int,
        *,
        api_preference: str | None = None,
        ffmpeg_options: str | None = None,
        use_timestamps: bool = True,
        buffer_size: int | None = None,
        properties: Sequence[tuple[str, float]] = (),
    ) -> None:
        self.target = target
        self.backend = "OpenCV"
        self.width = 0
        self.height = 0
        self.fps = DEFAULT_FPS
        self.has_container_pts = False
        self._api_preference = api_preference
        self._ffmpeg_options = ffmpeg_options
        self._use_timestamps = use_timestamps
        self._buffer_size = buffer_size
        self._properties = tuple(properties)
        self._cap: Any = None
        self._cv2: Any = None
        self._last_pos_ms: float | None = None
        self._flat_pos_count = 0

    def open(self) -> None:
        """Open the capture.

        Raises:
            MissingDependencyError: OpenCV is not installed.
            SourceUnavailableError: the capture would not open.
        """
        try:
            import cv2  # noqa: PLC0415 -- lazy on purpose
        except ImportError as exc:
            raise MissingDependencyError(
                "cv2", f"capturing {self.target!r}", "pip install opencv-python-headless"
            ) from exc
        self._cv2 = cv2
        if self._ffmpeg_options:
            # OpenCV's FFmpeg backend takes demuxer options only through this
            # environment variable, read when VideoCapture is constructed --
            # there is no per-capture API. setdefault so an operator who set it
            # deliberately in the environment still wins.
            os.environ.setdefault("OPENCV_FFMPEG_CAPTURE_OPTIONS", self._ffmpeg_options)
        api = getattr(cv2, self._api_preference, None) if self._api_preference else None
        try:
            cap = cv2.VideoCapture(self.target, api) if api is not None else cv2.VideoCapture(self.target)
        except Exception as exc:
            raise SourceUnavailableError(f"OpenCV could not open {self.target!r}: {exc}") from exc
        if not cap.isOpened():
            cap.release()
            raise SourceUnavailableError(f"OpenCV could not open {self.target!r}")
        # Order matters on UVC devices: the pixel format has to be set before
        # the frame size, or the driver silently keeps the old format and
        # caps the resolution (the classic "1080p capture card runs at 5 fps"
        # trap -- it fell back to raw YUY2 over USB 2).
        for name, value in self._properties:
            prop = getattr(cv2, name, None)
            if prop is None:
                continue
            cap.set(prop, value)
        if self._buffer_size is not None:
            # One-frame buffer: on a live source we want the newest frame, not
            # a queue of stale ones. Not honoured by every backend.
            cap.set(cv2.CAP_PROP_BUFFERSIZE, float(self._buffer_size))
        self._cap = cap
        self.width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 0)
        self.height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 0)
        reported = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)
        self.fps = reported if 0.0 < reported < 1000.0 else DEFAULT_FPS

    def next(self) -> tuple[np.ndarray, float | None] | None:
        """Grab the next frame, with its container timestamp when there is one."""
        if self._cap is None:
            raise SourceUnavailableError("OpenCVReader.next() before open()")
        cv2 = self._cv2
        pos_ms: float | None = None
        if self._use_timestamps:
            # Read the position *before* read(). With the FFmpeg backend
            # CAP_PROP_POS_MSEC advances as soon as a frame is grabbed, so
            # reading it afterwards gives the timestamp of the *next* frame --
            # a one-frame overlay offset that is invisible until something is
            # moving fast, which is exactly when it matters.
            raw = self._cap.get(cv2.CAP_PROP_POS_MSEC)
            if raw is not None and math.isfinite(raw) and raw >= 0.0:
                pos_ms = float(raw)
        try:
            ok, image = self._cap.read()
        except Exception as exc:
            raise SourceUnavailableError(f"read failed on {self.target!r}: {exc}") from exc
        if not ok or image is None:
            return None
        if image.ndim == 2:  # some capture drivers hand back single-channel
            image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
        if not self.width or not self.height:
            self.height, self.width = int(image.shape[0]), int(image.shape[1])
        pts = self._vet_timestamp(pos_ms)
        if pts is not None:
            self.has_container_pts = True
        return image, pts

    def _vet_timestamp(self, pos_ms: float | None) -> float | None:
        """Reject a position counter that is not actually a clock.

        Plenty of backends return a constant 0.0 for POS_MSEC. Feeding that to
        the pts clock would produce a monotonicity repair on every single frame
        and a timeline made entirely of 1 ms steps, which would look valid and
        be nonsense. Detect it once, then stop asking.
        """
        if pos_ms is None:
            return None
        if self._last_pos_ms is not None and pos_ms <= self._last_pos_ms:
            self._flat_pos_count += 1
            if self._flat_pos_count >= 3:
                self._use_timestamps = False
                return None
            return None
        self._last_pos_ms = pos_ms
        self._flat_pos_count = 0
        return pos_ms / 1000.0

    def close(self) -> None:
        """Release the capture. Safe to call twice."""
        cap, self._cap = self._cap, None
        if cap is not None:
            try:
                cap.release()
            except Exception:  # pragma: no cover
                pass


def _rate_of(stream: Any) -> float:
    """Best available nominal frame rate for a PyAV video stream."""
    for attr in ("average_rate", "guessed_rate", "base_rate"):
        rate = getattr(stream, attr, None)
        if rate:
            try:
                value = float(rate)
            except (TypeError, ValueError):
                continue
            if 0.0 < value < 1000.0:
                return value
    return DEFAULT_FPS


class FrameSource(abc.ABC):
    """Abstract video source: open it, iterate frames, close it.

    Subclasses implement three hooks -- :meth:`_open_impl`, :meth:`_read_raw`
    and :meth:`_close_impl` -- and inherit pts normalisation, rate decimation,
    frame numbering and statistics from here, so that every source in the
    system produces timestamps with identical semantics. That uniformity is
    the point of the seam: a bug in pts handling should be fixable in one
    place, not five.

    Usage::

        with open_source(cfg) as src:
            for frame in src:
                ...

    Threading: a source is read by one thread. :meth:`close` is the exception
    and may be called from another thread to break a blocking read or a
    reconnect backoff.
    """

    def __init__(self, cfg: SourceConfig, *, source_type: str, uri: str | None = None) -> None:
        self.cfg = cfg
        self._info = SourceInfo(
            type=source_type,
            uri=uri if uri is not None else cfg.uri,
            target_fps=cfg.target_fps,
        )
        self._stats = SourceStats()
        self._decimator = FpsDecimator(cfg.target_fps)
        self._clock: PtsClock | None = None
        self._next_frame_id = 0
        self._opened = False
        self._ended = False
        self._closing = False

    # -- public API ---------------------------------------------------------

    @property
    def info(self) -> SourceInfo:
        """Resolution, rate, URI, backend and pts provenance.

        Populated by :meth:`open` and refined once the first frame confirms the
        real frame size and whether the source had timestamps at all.
        """
        return self._info

    @property
    def stats(self) -> SourceStats:
        """Live counters. The same object throughout the source's life."""
        return self._stats

    @property
    def is_open(self) -> bool:
        return self._opened

    @property
    def is_exhausted(self) -> bool:
        """True once :meth:`read` has returned ``None``."""
        return self._ended

    def open(self) -> "FrameSource":
        """Open the underlying source. Idempotent.

        Returns:
            ``self``, so ``src = FileSource(cfg).open()`` reads well.

        Raises:
            MissingDependencyError: the backend this source needs is absent.
            SourceUnavailableError: the source exists but would not open.
        """
        if self._opened:
            return self
        self._closing = False
        self._open_impl()
        self._opened = True
        self._ended = False
        self._stats.opened_monotonic = time.monotonic()
        return self

    def close(self) -> None:
        """Release the source. Idempotent, and safe from another thread."""
        self._closing = True
        if not self._opened:
            self._close_impl()
            return
        self._opened = False
        self._close_impl()

    def read(self) -> Frame | None:
        """Return the next frame, or ``None`` when the source is finished.

        A live source only returns ``None`` when it has given up reconnecting
        or has been closed; a file returns ``None`` at end of file (unless
        ``SourceConfig.loop``).

        Raises:
            IngestError: the source has not been opened.
        """
        if not self._opened:
            raise IngestError(f"{type(self).__name__}.read() called before open()")
        clock = self._clock
        if clock is None:  # pragma: no cover - _open_impl always sets it
            raise IngestError(f"{type(self).__name__} did not initialise its pts clock")
        while True:
            raw = self._read_raw()
            if raw is None:
                self._ended = True
                return None
            image, raw_pts = raw
            self._stats.frames_in += 1
            pts = clock.stamp(raw_pts)
            self._stats.pts_repairs = clock.repairs
            self._stats.pts_synthesised = clock.synthesised
            if not self._decimator.accept(pts):
                self._stats.decimated = self._decimator.dropped
                continue
            frame = Frame(
                image=image,
                frame_id=self._next_frame_id,
                pts=pts,
                wall_time=utc_now_iso(),
                rtp_ts=None,  # only the sender knows the real one; see module docstring
                source_pts=raw_pts,
                pts_synthesised=raw_pts is None,
            )
            self._next_frame_id += 1
            self._stats.frames_out += 1
            if self._next_frame_id == 1:
                self._observe_first_frame(frame, clock)
            return frame

    def __iter__(self) -> Iterator[Frame]:
        """Iterate frames until the source is exhausted, opening it if needed."""
        if not self._opened:
            self.open()
        return self

    def __next__(self) -> Frame:
        frame = self.read()
        if frame is None:
            raise StopIteration
        return frame

    def __enter__(self) -> "FrameSource":
        return self.open()

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        self.close()

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self._info.describe()})"

    # -- helpers for subclasses --------------------------------------------

    def _set_info(self, **changes: Any) -> None:
        """Update the published :class:`SourceInfo`."""
        self._info = replace(self._info, **changes)

    def _add_note(self, note: str) -> None:
        """Record an operator-facing caveat, once."""
        if note not in self._info.notes:
            self._info = replace(self._info, notes=self._info.notes + (note,))

    def _init_clock(self, mode: str, fps: float | None = None) -> PtsClock:
        """Create the pts clock. Every ``_open_impl`` must call this."""
        self._clock = PtsClock(nominal_fps=fps if fps is not None else self._info.fps, mode=mode)
        return self._clock

    def _observe_first_frame(self, frame: Frame, clock: PtsClock) -> None:
        """Correct :attr:`info` once reality is known.

        The header's idea of the frame size is not always right, and whether a
        container really carries timestamps is only knowable after decoding
        something. Publishing the guess and never correcting it would leave
        ``pts_origin`` claiming ``container`` on a stream that has none.
        """
        changes: dict[str, Any] = {"pts_origin": clock.origin}
        if frame.width and frame.height and (frame.width, frame.height) != self._info.resolution:
            changes["width"] = frame.width
            changes["height"] = frame.height
        self._set_info(**changes)
        if clock.origin == PtsOrigin.FRAME_INDEX:
            self._add_note(
                f"source supplied no timestamps; pts synthesised from frame index at "
                f"{self._info.fps:.4g} fps"
            )
        elif clock.origin == PtsOrigin.WALL_CLOCK:
            self._add_note("device capture; pts taken from frame arrival time")

    # -- subclass hooks -----------------------------------------------------

    @abc.abstractmethod
    def _open_impl(self) -> None:
        """Open the backend and call :meth:`_init_clock`."""

    @abc.abstractmethod
    def _read_raw(self) -> tuple[np.ndarray, float | None] | None:
        """Return ``(bgr_image, raw_pts_or_None)``, or ``None`` when finished."""

    @abc.abstractmethod
    def _close_impl(self) -> None:
        """Release backend resources. Must tolerate being called twice."""


class ReconnectingSource(FrameSource):
    """A :class:`FrameSource` backed by a reader that may fail and be re-opened.

    Shared by every live source (RTSP, RTMP, HDMI). The behaviour it exists to
    guarantee: *a link that drops comes back without anybody touching the
    laptop*. Ground stations are set up on a truck bonnet and then everyone
    walks away from them.

    Two details that are easy to get wrong and matter downstream:

    * The media timeline advances across the outage by the measured wall-clock
      gap, so a 12 s dropout leaves a 12 s hole in pts rather than pretending
      the frames were contiguous. The incident log then shows what was really
      missed.
    * The decimator is reset at the seam, so the first frame after a reconnect
      is always delivered rather than waiting out a rate-limit schedule
      inherited from before the outage.
    """

    def __init__(
        self,
        cfg: SourceConfig,
        *,
        source_type: str,
        uri: str | None = None,
        max_reconnect_attempts: int | None = None,
        max_backoff_s: float = 15.0,
    ) -> None:
        super().__init__(cfg, source_type=source_type, uri=uri)
        self._reader: FrameReader | None = None
        self._policy = ReconnectPolicy(
            base_delay_s=cfg.reconnect_s,
            max_delay_s=max_backoff_s,
            max_attempts=max_reconnect_attempts,
        )
        self._outage_started: float | None = None

    @abc.abstractmethod
    def _connect(self) -> FrameReader:
        """Build and open a fresh reader, or raise.

        Returning an already-open reader (rather than one this class opens) is
        what lets a subclass try several backends and pick whichever came up.
        """

    def _pts_mode(self) -> str:
        """Preferred pts origin. Overridden by capture devices."""
        return PtsOrigin.CONTAINER

    def _open_impl(self) -> None:
        reader = self._connect()
        self._reader = reader
        self._set_info(
            width=reader.width,
            height=reader.height,
            fps=reader.fps,
            backend=reader.backend,
            is_live=True,
        )
        self._init_clock(self._pts_mode(), reader.fps)
        self._stats.reconnecting = False

    def _read_raw(self) -> tuple[np.ndarray, float | None] | None:
        while True:
            item: tuple[np.ndarray, float | None] | None = None
            if self._reader is not None:
                try:
                    item = self._reader.next()
                except IngestError as exc:
                    self._stats.decode_errors += 1
                    self._stats.last_error = str(exc)
                    item = None
            if item is not None:
                if self._stats.reconnecting:
                    self._finish_outage()
                self._policy.reset()
                return item
            if self._closing or self._policy.exhausted or self._policy.cancelled:
                return None
            if not self._reconnect():
                return None

    def _reconnect(self) -> bool:
        """Tear down, back off, and try again.

        Returns:
            True if a reader is open again, False if the source should stop
            (closed, cancelled, or out of attempts).
        """
        if self._outage_started is None:
            self._outage_started = time.monotonic()
        self._stats.reconnecting = True
        if self._reader is not None:
            try:
                self._reader.close()
            except Exception:  # pragma: no cover - closing a broken socket
                pass
            self._reader = None
        while not self._closing:
            if not self._policy.wait():  # cancelled by close()
                return False
            if self._policy.exhausted:
                self._stats.last_error = (
                    f"giving up on {self._info.uri!r} after {self._policy.attempts} attempts"
                )
                return False
            try:
                reader = self._connect()
            except MissingDependencyError:
                raise  # retrying will not install a package
            except IngestError as exc:
                self._stats.last_error = str(exc)
                continue
            self._reader = reader
            self._stats.reconnects += 1
            if reader.width and reader.height:
                self._set_info(width=reader.width, height=reader.height, backend=reader.backend)
            return True
        return False

    def _finish_outage(self) -> None:
        """Close the timeline gap once frames are flowing again."""
        gap = 0.0
        if self._outage_started is not None:
            gap = max(0.0, time.monotonic() - self._outage_started)
        self._outage_started = None
        self._stats.reconnecting = False
        clock = self._clock
        if clock is not None:
            # The stream restarted its own clock at zero. Continue our timeline
            # forward by the real outage so pts keeps meaning "time since the
            # session began" -- a timeline that rewound would make the tablet
            # match fresh detections against frames from before the dropout.
            clock.discontinuity(gap)
        self._decimator.reset()
        self._add_note(f"reconnected after {gap:.1f}s")

    def _close_impl(self) -> None:
        self._policy.cancel()
        reader, self._reader = self._reader, None
        if reader is not None:
            try:
                reader.close()
            except Exception:  # pragma: no cover
                pass
